# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: install yarn
      run: npm install -g yarn


    - name: Get yarn cached directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      #this returns the dir of the yarn cache. returning it in a variable called dir


    - name: cache node modules
      uses: actions/cache@v2
      id: cache-node-modules-job
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **\node-modules
      #gets the previously set cache dir name 
        key : ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      if: steps.cache-node-modules-job.outputs.cache-hit != 'true'
      run: yarn
    - name: test
      run: yarn test
